ALTER TABLE users ADD COLUMN full_name VARCHAR(150) NOT NULL DEFAULT '' AFTER id;
ALTER TABLE users ADD COLUMN phone_number VARCHAR(20) NOT NULL DEFAULT '' AFTER full_name;
ALTER TABLE users ADD COLUMN nid_number VARCHAR(50) DEFAULT NULL AFTER email;
ALTER TABLE users ADD COLUMN date_of_birth DATE DEFAULT NULL AFTER nid_number;
ALTER TABLE users ADD COLUMN address TEXT DEFAULT NULL AFTER date_of_birth;
